name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev qtbase5-dev qttools5-dev

      - name: Build
        run: |
          export JAVA_HOME=$JAVA_HOME_8_X64
          mkdir build
          cd build
          cmake \
           -DCMAKE_BUILD_TYPE=Release \
           -DLauncher_NOTIFICATION_URL:STRING=https://files.multimc.org/notifications.json \
           -DCMAKE_INSTALL_PREFIX:PATH=/home/runner/UltimMC/UltimMC \
           -DLauncher_UPDATER_BASE=https://files.multimc.org/update/ \
           -DLauncher_PASTE_EE_API_KEY:STRING=utLvciUouSURFzfjPxLBf5W4ISsUX4pwBDF7N1AfZ \
           -DLauncher_ANALYTICS_ID:STRING=UA-87731965-2 \
           -DLauncher_LAYOUT=lin-nodeps \
           -DLauncher_BUILD_PLATFORM=lin64 \
           -DLauncher_BUG_TRACKER_URL=https://github.com/UltimMC/Launcher/issues \
           -DLauncher_EMBED_SECRETS=On \
           $GITHUB_WORKSPACE

      - name: Compile
        run: |
          cd build
          make -j$(nproc)

      - name: Test
        run: |
          cd build
          make test
          cmake -E remove_directory "/home/runner/UltimMC/UltimMC"

      - name: Install
        run: |
          cd build
          make install
          chmod +x /home/runner/UltimMC/UltimMC/UltimMC
          chmod +x /home/runner/UltimMC/UltimMC/bin/UltimMC

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mmc-cracked-lin64
          path: /home/runner/UltimMC

  build-windows:
    name: build-windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81'
          tools: 'tools_mingw,qt.tools.win64_mingw810'

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
          architecture: x64

      - name: Build
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake ^
           -DCMAKE_C_COMPILER=gcc ^
           -DCMAKE_CXX_COMPILER=g++ ^
           -DCMAKE_BUILD_TYPE=Release ^
           -DLauncher_NOTIFICATION_URL:STRING=https://files.multimc.org/notifications.json ^
           -DCMAKE_INSTALL_PREFIX:PATH="D:/UltimMC/UltimMC" ^
           -DLauncher_UPDATER_BASE=https://files.multimc.org/update/ ^
           -DLauncher_PASTE_EE_API_KEY:STRING=utLvciUouSURFzfjPxLBf5W4ISsUX4pwBDF7N1AfZ ^
           -DLauncher_ANALYTICS_ID:STRING=UA-87731965-2 ^
           -DLauncher_LAYOUT=win-bundle ^
           -DLauncher_BUILD_PLATFORM=win64 ^
           -DLauncher_BUG_TRACKER_URL=https://github.com/UltimMC/Launcher/issues ^
           -DLauncher_EMBED_SECRETS=On ^
           -G "MinGW Makefiles" ^
           ..

      - name: Compile
        shell: cmd
        run: |
          cd build
          mingw32-make -j%NUMBER_OF_PROCESSORS%

      - name: Test
        shell: cmd
        run: |
          cd build
          mingw32-make test
          cmake -E remove_directory "D:/UltimMC/UltimMC"

      - name: Install
        shell: cmd
        run: |
          cd build
          mingw32-make install

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mmc-cracked-win64
          path: "D:/UltimMC"

  build-mac:
    name: build-mac
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: /Users/runner/Library/Caches/Homebrew
          key: ${{ runner.os }}-deps-cache

      - name: Install Dependencies
        run: |
          brew cleanup
          brew install qt@5

      - name: Build
        run: |
          mkdir build
          cd build
          cmake \
           -DCMAKE_C_COMPILER=/usr/bin/clang \
           -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
           -DCMAKE_BUILD_TYPE=Release \
           -DLauncher_NOTIFICATION_URL:STRING=https://files.multimc.org/notifications.json \
           -DCMAKE_INSTALL_PREFIX:PATH="/Users/runner/work/UltimMC/build/dist" \
           -DCMAKE_PREFIX_PATH="$(brew --prefix qt@5)/lib/cmake" \
           -DQt5_DIR="$(brew --prefix qt@5)" \
           -DLauncher_UPDATER_BASE=https://files.multimc.org/update/ \
           -DLauncher_PASTE_EE_API_KEY:STRING=utLvciUouSURFzfjPxLBf5W4ISsUX4pwBDF7N1AfZ \
           -DLauncher_ANALYTICS_ID:STRING=UA-87731965-2 \
           -DLauncher_LAYOUT=mac-bundle \
           -DLauncher_BUILD_PLATFORM=osx64-5.15.2 \
           -DLauncher_BUG_TRACKER_URL=https://github.com/UltimMC/Launcher/issues \
           -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 \
           -DLauncher_EMBED_SECRETS=On \
           $GITHUB_WORKSPACE

      - name: Compile
        run: |
          cd build
          make -j$(sysctl -n hw.logicalcpu)

      - name: Test
        run: |
          cd build
          make test
          cmake -E remove_directory "/Users/runner/work/UltimMC/build/dist"

      - name: Install
        run: |
          cd build
          make install
          chmod +x /Users/runner/work/UltimMC/build/dist/UltimMC.app/Contents/MacOS/UltimMC

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mmc-cracked-osx64
          path: /Users/runner/work/UltimMC/build/dist
